version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start